#!/usr/bin/env python3
"""Generate the synthetic example starlist (synthetic_k1lgs.lst).

Every target in the output is FAKE -- names, coordinates, and magnitudes are
drawn from a fixed-seed RNG, so the file carries no real observing-program
information and can ship publicly. It deliberately reproduces the formatting
quirks of real hand-edited Keck starlists that starlist.py was ground-truthed
against (see src/keck_ao_estimator/starlist.py), so it stays a faithful
regression fixture:

  * fixed 16-column name field, including names that contain spaces
  * one name WIDER than 16 columns (exercises the RA/Dec-locator fallback)
  * Dec with and without a leading '+', including a negative-zero degree
    field ("-00 12 34.5"), equinox as "2000.0", bare "2000", and "APP"
  * key=value fields: vmag/rmag/imag, b-v/b-r, bare J= H= K=, lgs=, pa=,
    sep=, vistt=/irtt=, comments=
  * tip-tilt star rows linked by target= (underscores standing in for
    spaces in the linked name), indented like the real lists
  * a trailing "# ..." comment that itself carries key=value fields
  * blank lines, full-line comments, and one malformed line (exercises the
    skipped-lines path -- one bad line must never lose the rest)

Regenerate with:  python make_synthetic_starlist.py
The output is deterministic (fixed seed); the committed synthetic_k1lgs.lst
should always match a fresh run.
"""
import math
import random
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "synthetic_k1lgs.lst")
SEED = 20260807
N_PLAIN = 20          # simple one-line science targets
N_LINKED = 8          # science targets that also get linked TT-star rows


def _fmt_ra(rng):
    return rng.randrange(24), rng.randrange(60), rng.uniform(0, 59.99)


def _fmt_dec(rng):
    # Keck-observable band; a few negative-zero declinations on purpose
    deg = rng.randrange(-25, 65)
    return deg, rng.randrange(60), rng.uniform(0, 59.9)


def _radec_deg(rng):
    """Random Keck-observable position, in degrees."""
    return rng.uniform(0, 360), rng.uniform(-25, 64)


def _fmt_radec(ra_deg, dec_deg, plus_sign=True, negzero=False):
    ra = ra_deg / 15.0
    rh = int(ra); rm = int((ra - rh) * 60); rs = ((ra - rh) * 60 - rm) * 60
    ad = abs(dec_deg)
    dd = int(ad); dm = int((ad - dd) * 60); ds = ((ad - dd) * 60 - dm) * 60
    if negzero and dd == 0 and dec_deg < 0:
        dec = f"-00 {dm:02d} {ds:04.1f}"
    else:
        sign = "-" if dec_deg < 0 else ("+" if plus_sign else "")
        dec = f"{sign}{dd:02d} {dm:02d} {ds:04.1f}"
    return f"{rh:02d} {rm:02d} {rs:05.2f} {dec}"


def _radec_str(rng, plus_sign=True, negzero=False):
    ra_deg, dec_deg = _radec_deg(rng)
    if negzero:
        dec_deg = -rng.uniform(0.1, 0.9)      # negative-zero degree field
    return _fmt_radec(ra_deg, dec_deg, plus_sign, negzero)


def _tt_radec_str(rng, ra_deg, dec_deg, sep_as):
    """A position sep_as arcsec from (ra_deg, dec_deg) at a random PA --
    linked TT stars must actually LIE at their claimed separation, so code
    that computes true angular separations sees a physical field."""
    pa = rng.uniform(0, 2 * math.pi)
    dra = sep_as * math.sin(pa) / math.cos(math.radians(dec_deg)) / 3600.0
    ddec = sep_as * math.cos(pa) / 3600.0
    return _fmt_radec(ra_deg + dra, dec_deg + ddec)


def main():
    rng = random.Random(SEED)
    lines = [
        "# synthetic_k1lgs.lst -- SYNTHETIC example starlist, all targets fake.",
        "# Generated by make_synthetic_starlist.py (fixed seed; regenerate at will).",
        "# Format: https://www2.keck.hawaii.edu/inst/ao/starlist.html",
        "",
    ]

    # engineering-style bright TT check stars (the real lists open the same way)
    for i in range(6):
        name = f"syneng{100 + i}"
        vmag = round(rng.uniform(9.9, 10.3), 2)
        bv = round(rng.uniform(0.4, 0.8), 2)
        lines.append(f"{name:<16} {_radec_str(rng)} 2000.0 "
                     f"vmag={vmag} b-v={bv} lgs=1")

    lines.append("")

    # plain science targets: mixed equinox styles, magnitudes, comments
    for i in range(N_PLAIN):
        name = f"SYN-{i + 1:03d}"
        eq = ["2000.0", "2000", "2000.0", "2000"][i % 4]
        kv = []
        if i % 3 == 0:
            kv.append(f"imag={round(rng.uniform(14.5, 18.5), 1)}")
        else:
            kv.append(f"vmag={round(rng.uniform(11.0, 16.0), 1)}")
        kv.append("lgs=1")
        if i % 5 == 0:
            kv.append("comments=lowpriority")
        if i % 7 == 3:
            kv.append("pa=0.00")
        line = f"{name:<16} {_radec_str(rng, plus_sign=(i % 2 == 0), negzero=(i == 4))} {eq} " + " ".join(kv)
        if i % 6 == 2:  # trailing comment that still carries key=value fields
            line += (f" # rmag={round(rng.uniform(12.0, 16.0), 2)}"
                     f" kmag={round(rng.uniform(9.0, 13.0), 2)}")
        lines.append(line)

    lines.append("")
    lines.append("# linked tip-tilt candidates (target= rows, indented like real lists)")

    # science targets with linked TT-star rows; some names contain spaces,
    # one is wider than the 16-column name field
    tt_no = 300
    specials = ["Syn Cluster A", "BD+99  1234", "SYNTHETIC WIDE FIELD 1", "APPSYN-1"]
    for i in range(N_LINKED):
        if i < len(specials):
            name = specials[i]
        else:
            name = f"SYNFLD{i:02d}"
        eq = "APP" if name == "APPSYN-1" else "2000.0"
        link = name.replace(" ", "_")
        ra_deg, dec_deg = _radec_deg(rng)
        # vmag= as well as imag=: the GUI's pick path falls back to a live
        # SIMBAD magnitude query when a picked row has no optical magnitude,
        # and the regression tests must never depend on the network
        lines.append(f"{name:<16} {_fmt_radec(ra_deg, dec_deg)} {eq} "
                     f"vmag={round(rng.uniform(13.0, 16.0), 1)} "
                     f"imag={round(rng.uniform(15.0, 18.5), 1)} lgs=1 irtt=1")
        for _ in range(2 if i % 2 == 0 else 1):
            tt_no += 1
            sep = round(rng.uniform(3.0, 55.0), 2)
            kv = [f"rmag={round(rng.uniform(13.5, 17.0), 2)}",
                  f"sep={sep}",
                  f"b-v={round(rng.uniform(0.4, 1.6), 2)}",
                  f"b-r={round(rng.uniform(0.8, 2.8), 2)}"]
            if rng.random() < 0.5:
                kv.append(f"J={round(rng.uniform(14.0, 16.0), 2)} "
                          f"H={round(rng.uniform(13.5, 15.5), 2)} "
                          f"K={round(rng.uniform(13.0, 15.0), 2)}")
            if rng.random() < 0.4:
                kv.append("vistt=0 irtt=1")
            lines.append(f"        syntt{tt_no:03d} "
                         f"{_tt_radec_str(rng, ra_deg, dec_deg, sep)} {eq} "
                         + " ".join(kv) + f" target={link}")

    lines.append("")
    lines.append("# one malformed line on purpose: parsers must skip it, not abort")
    lines.append("SYN-BADLINE      not a coordinate at all")
    lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
