#!/usr/bin/env python3
"""Keck starlist parsing contract (starlist.parse_starlist), headless,
pinned against the SYNTHETIC starlist bundled in examples/
(synthetic_k1lgs.lst, generated by examples/make_synthetic_starlist.py --
fake targets reproducing real hand-edited lists' quirks): fixed-width
16-column names that may contain spaces, unsigned positive Decs,
negative-zero Decs, bare "2000" equinoxes, key=value fields both before and
inside the trailing '#' comment, and explicit target= TT-star links.
The values asserted here are those of the COMMITTED fixture: if the
generator changes and the list is regenerated, update them together."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE); sys.path.insert(0, ROOT); os.chdir(ROOT)
sys.path.insert(0, os.path.join(os.path.dirname(ROOT), "src"))
import warnings
warnings.filterwarnings("ignore")
import keck_ao_estimator as engine

SAMPLE = os.path.join(ROOT, "examples", "synthetic_k1lgs.lst")


def bundled_file():
    entries, skipped = engine.parse_starlist(SAMPLE)
    assert len(entries) == 46, f"expected 46 entries, got {len(entries)}"
    # exactly the one DELIBERATE bad line, skipped with its line number
    assert len(skipped) == 1 and "SYN-BADLINE" in skipped[0][1], skipped
    print(f"  [ok] bundled synthetic starlist: {len(entries)} entries, the "
          f"one deliberate bad line skipped (line {skipped[0][0]})")

    byname = {e["name"]: e for e in entries}

    # trailing-'#'-comment key=values (SYN-003: "... lgs=1 # rmag=12.5 kmag=9.86")
    e = byname["SYN-003"]
    assert e["keys"]["vmag"] == "11.8" and e["lgs"]
    assert e["keys"]["rmag"] == "12.5" and e["keys"]["kmag"] == "9.86", \
        "key=value fields inside the trailing '#' comment must be parsed"
    assert engine.entry_float(e, "rmag") == 12.5
    print("  [ok] '#'-comment rmag/kmag parsed "
          f"(R={e['keys']['rmag']}, K={e['keys']['kmag']})")

    # the parser's ra/dec STRINGS must agree with its own ra_deg/dec_deg
    # through the same engine.parse_radec the GUI fields use
    for e2 in (entries[0], byname["Syn Cluster A"], byname["APPSYN-1"]):
        c = engine.parse_radec(e2["ra"], e2["dec"])
        assert abs(c.ra.deg - e2["ra_deg"]) * 3600 < 0.01, e2["name"]
        assert abs(c.dec.deg - e2["dec_deg"]) * 3600 < 0.01, e2["name"]
    print("  [ok] ra/dec strings round-trip through engine.parse_radec to "
          "<0.01\" of the parsed degrees")

    # fixed-width name field WITH internal spaces
    syn = byname["Syn Cluster A"]
    assert syn["equinox"] == "2000.0" and syn["lgs"]
    assert abs(syn["ra_deg"] - (12 + 28 / 60 + 20.42 / 3600) * 15) < 1e-9

    # bare "2000" equinox + UNSIGNED positive Dec (SYN-002)
    syn2 = byname["SYN-002"]
    assert syn2["equinox"] == "2000"
    assert syn2["dec_deg"] > 0 and syn2["dec"].startswith("+23:"), \
        "unsigned positive Dec must normalize with an explicit '+'"

    # negative-zero Dec in the bundled file (SYN-005: "-00 09 19.6")
    syn5 = byname["SYN-005"]
    assert syn5["dec_deg"] < 0 and abs(
        syn5["dec_deg"] + (9 / 60 + 19.6 / 3600)) < 1e-9, \
        "Dec '-00 09 19.6' must stay south"

    # a name WIDER than the 16-column field (RA/Dec-pattern fallback)
    wide = byname["SYNTHETIC WIDE FIELD 1"]
    assert abs(wide["ra_deg"] - (13 + 33 / 60 + 35.31 / 3600) * 15) < 1e-9

    # explicit target= link: TT-star row -> its science target, with the
    # bare J= H= K= magnitude keys (NOT 'jmag='/'kmag=' on these rows)
    tt = byname["syntt303"]
    assert tt["target"] == "BD+99__1234", tt["target"]
    assert engine.entry_float(tt, "kmag", "K") == 13.59, \
        "bare K= key must be reachable (kmag= tried first, then K=)"
    assert engine.entry_float(tt, "sep") == 48.68
    # and its science target row is NOT itself linked
    sci = byname["BD+99  1234"]
    assert sci["target"] is None
    print("  [ok] target= TT-star link (syntt303 -> BD+99__1234), bare "
          "J/H/K= keys, sep=; science row itself unlinked; wide + spaced "
          "names, unsigned and negative-zero Decs")


def malformed_and_edges():
    text = """\
# a full-line comment, skipped silently

GoodStar        01 02 03.4 -05 06 07.8 2000.0 vmag=9
this line is complete garbage
BadRA           25 00 00.0 +10 00 00.0 2000.0
NegZeroDec      10 20 30.0 -00 30 00.0 2000.0
AVeryLongNameOverflowingTheField 11 22 33.4 +44 55 06.6 2000.0 vmag=8
Precessed       01 02 03.4 +05 06 07.8 1950.0
"""
    entries, skipped = engine.parse_starlist_text(text)
    assert [e["name"] for e in entries] == [
        "GoodStar", "NegZeroDec", "AVeryLongNameOverflowingTheField",
        "Precessed"], [e["name"] for e in entries]
    assert len(skipped) == 2, skipped
    assert skipped[0][0] == 4 and skipped[1][0] == 5, \
        "skipped lines must carry their line numbers"
    print("  [ok] malformed lines are skipped WITH line numbers, the rest "
          "of the list survives")

    # negative-zero degrees: "-00 30 00" must stay SOUTH -- a float() on the
    # degrees field would silently lose the sign
    nz = entries[1]
    assert nz["dec_deg"] < 0 and abs(nz["dec_deg"] + 0.5) < 1e-9, \
        f"-00 30 00 must be -0.5 deg, got {nz['dec_deg']}"
    c = engine.parse_radec(nz["ra"], nz["dec"])
    assert abs(c.dec.deg + 0.5) * 3600 < 0.01
    print("  [ok] Dec \"-00 30 00.0\" keeps its sign (-0.5 deg), string and "
          "degrees alike")

    # an over-wide name falls back to the RA/Dec-pattern locator
    wide = entries[2]
    assert abs(wide["ra_deg"] - (11 + 22 / 60 + 33.4 / 3600) * 15) < 1e-9
    assert wide["keys"]["vmag"] == "8"
    print("  [ok] a name wider than the standard 16 columns still parses "
          "(RA/Dec-pattern fallback)")

    # non-J2000 equinox is preserved for the GUI to warn about
    assert entries[3]["equinox"] == "1950.0"
    print("  [ok] non-J2000 equinox preserved verbatim")


def link_name_matching():
    """same_star_name: the target= linking convention. A key=value field is
    a whitespace-delimited token, so a target= value CANNOT contain spaces
    -- lists write underscores instead ('target=Syn_Cluster_A' linking to
    the name 'Syn Cluster A'), which an exact == comparison silently missed
    on a real list (2026-07-22 bug). The 16-column name field also pads
    with space RUNS a hand-written link never reproduces ('BD+99  1234' vs
    'BD+99__1234')."""
    assert engine.same_star_name("Syn_Cluster_A", "Syn Cluster A")
    assert engine.same_star_name("Syn Cluster A", "Syn_Cluster_A")
    assert engine.same_star_name("SYNFLD04", "SYNFLD04")   # no spaces
    assert engine.same_star_name("BD+99__1234", "BD+99  1234"), \
        "case + the padded name field's space runs must not break a link"
    assert not engine.same_star_name("Syn Cluster A", "Syn Cluster B")
    assert not engine.same_star_name("", "")
    assert not engine.same_star_name(None, None)
    print("  [ok] same_star_name: underscore<->space linking, case/run "
          "tolerant, empty never matches")


def main():
    bundled_file()
    malformed_and_edges()
    link_name_matching()


if __name__ == "__main__":
    main()
    print("  [ok] Keck starlist parsing contract holds")
